function decode(value) {
    return Buffer.from(value, 'base64').toString('utf8');
}

function decoded(values) {
    return values.map(decode);
}

const banned = {
    exact: new Set(decoded([
        'YWJ1c2Vy',
        'Y3NhbQ==',
        'bW9sZXN0ZXI=',
        'cGFlZG8=',
        'cGVkbw==',
        'cGVkZXJhc3Q=',
        'cmFwZQ==',
        'cmFwZXI=',
        'cmFwaXN0',
        'cmFwaW5n',
        'dHJhZmZpY2tlcg==',
    ])),
    contains: decoded([
        'YmFieXJhcGU=',
        'Y2hpbGRhYnVzZQ==',
        'Y2hpbGRtb2xlc3Q=',
        'Y2hpbGRwb3Ju',
        'Y2hpbGRyYXBl',
        'Y2hpbGRyYXBpc3Q=',
        'Y2hpbGRzZXg=',
        'Y2hpbGRyZW5yYXBl',
        'Y2hpbGRyZW5yYXBpc3Q=',
        'Y3Bvcm4=',
        'aW5mYW50cmFwZQ==',
        'a2lkbW9sZXN0',
        'a2lkcG9ybg==',
        'a2lkcmFwZQ==',
        'a2lkcmFwaXN0',
        'a2lkZGllbW9sZXN0',
        'a2lkZGllcG9ybg==',
        'a2lkZGllcmFwZQ==',
        'a2lkZGllcmFwaXN0',
        'bWlub3JhYnVzZQ==',
        'bWlub3Jtb2xlc3Q=',
        'bWlub3Jwb3Ju',
        'bWlub3JyYXBl',
        'bWlub3JyYXBpc3Q=',
        'bW9sZXN0Y2hpbGQ=',
        'bW9sZXN0aW5nY2hpbGQ=',
        'cGFlZG9waGlsZQ==',
        'cGFlZG9waGlsaWE=',
        'cGVkb3BoaWxl',
        'cGVkb3BoaWxpYQ==',
        'cmFwZWJhYmllcw==',
        'cmFwZWNoaWxk',
        'cmFwZWtpZHM=',
        'cmFwZW1pbm9y',
        'c2V4dHJhZmZpY2s=',
        'dHJhZmZpY2tjaGlsZHJlbg==',
        'dHJhZmZpY2traWRz',
        'dHJhZmZpY2ttaW5vcnM=',
    ]),
};

export const usernames = {
    reserved: new Set([
        'account',
        'accounts',
        'admin',
        'admins',
        'administrator',
        'bot',
        'bots',
        'developer',
        'download',
        'faucet',
        'firebase',
        'founder',
        'gliftec',
        'glyphteck',
        'help',
        'helpdesk',
        'legal',
        'login',
        'mod',
        'moderator',
        'official',
        'owner',
        'passkey',
        'privacy',
        'regtest',
        'report',
        'review',
        'reviewer',
        'root',
        'safety',
        'security',
        'service',
        'spark',
        'staff',
        'support',
        'sys',
        'system',
        'team',
        'terms',
        'test',
        'trust',
        'veyl',
        'wallet',
    ]),
    banned,
};
